name: Flask app
run-name: ${{ github.actor }} is performing GitHub Actions
on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Set up Python 3.12 environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          make install

      # Lint with Pylint
      - name: Lint with Pylint
        run: |
          make lint

      # Test with Pytest
      - name: Test with Pytest
        run: |
          make test

      # Format code with Python black
      - name: Format code with Python black
        run: |
          make format

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $AWS_DEFAULT_REGION 

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t processor:latest .

      # Tag the Docker image with the ECR repository URI
      - name: Tag Docker image
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ECR_REPOSITORY_NAME: processor
        run: docker tag processor:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/processor:latest

      # Push the Docker image to Amazon ECR
      - name: Push Docker image to Amazon ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ECR_REPOSITORY_NAME: processor
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/processor:latest
